# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mihau/workspace/pong-arduino-mock

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mihau/workspace/pong-arduino-mock

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihau/workspace/pong-arduino-mock/CMakeFiles /home/mihau/workspace/pong-arduino-mock/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihau/workspace/pong-arduino-mock/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pong_arduino_mock

# Build rule for target.
pong_arduino_mock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pong_arduino_mock
.PHONY : pong_arduino_mock

# fast build rule for target.
pong_arduino_mock/fast:
	$(MAKE) -f CMakeFiles/pong_arduino_mock.dir/build.make CMakeFiles/pong_arduino_mock.dir/build
.PHONY : pong_arduino_mock/fast

#=============================================================================
# Target rules for targets named pong_arduino_mock-size

# Build rule for target.
pong_arduino_mock-size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pong_arduino_mock-size
.PHONY : pong_arduino_mock-size

# fast build rule for target.
pong_arduino_mock-size/fast:
	$(MAKE) -f CMakeFiles/pong_arduino_mock-size.dir/build.make CMakeFiles/pong_arduino_mock-size.dir/build
.PHONY : pong_arduino_mock-size/fast

#=============================================================================
# Target rules for targets named pong_arduino_mock-upload

# Build rule for target.
pong_arduino_mock-upload: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pong_arduino_mock-upload
.PHONY : pong_arduino_mock-upload

# fast build rule for target.
pong_arduino_mock-upload/fast:
	$(MAKE) -f CMakeFiles/pong_arduino_mock-upload.dir/build.make CMakeFiles/pong_arduino_mock-upload.dir/build
.PHONY : pong_arduino_mock-upload/fast

#=============================================================================
# Target rules for targets named uno_.

# Build rule for target.
uno_.: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uno_.
.PHONY : uno_.

# fast build rule for target.
uno_./fast:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/build
.PHONY : uno_./fast

#=============================================================================
# Target rules for targets named uno_CORE

# Build rule for target.
uno_CORE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uno_CORE
.PHONY : uno_CORE

# fast build rule for target.
uno_CORE/fast:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/build
.PHONY : uno_CORE/fast

#=============================================================================
# Target rules for targets named upload

# Build rule for target.
upload: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload
.PHONY : upload

# fast build rule for target.
upload/fast:
	$(MAKE) -f CMakeFiles/upload.dir/build.make CMakeFiles/upload.dir/build
.PHONY : upload/fast

TVOlogo.obj: TVOlogo.cpp.obj

.PHONY : TVOlogo.obj

# target to build an object file
TVOlogo.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVOlogo.cpp.obj
.PHONY : TVOlogo.cpp.obj

TVOlogo.i: TVOlogo.cpp.i

.PHONY : TVOlogo.i

# target to preprocess a source file
TVOlogo.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVOlogo.cpp.i
.PHONY : TVOlogo.cpp.i

TVOlogo.s: TVOlogo.cpp.s

.PHONY : TVOlogo.s

# target to generate assembly for a file
TVOlogo.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVOlogo.cpp.s
.PHONY : TVOlogo.cpp.s

TVOut.obj: TVOut.cpp.obj

.PHONY : TVOut.obj

# target to build an object file
TVOut.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVOut.cpp.obj
.PHONY : TVOut.cpp.obj

TVOut.i: TVOut.cpp.i

.PHONY : TVOut.i

# target to preprocess a source file
TVOut.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVOut.cpp.i
.PHONY : TVOut.cpp.i

TVOut.s: TVOut.cpp.s

.PHONY : TVOut.s

# target to generate assembly for a file
TVOut.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVOut.cpp.s
.PHONY : TVOut.cpp.s

TVout.obj: TVout.cpp.obj

.PHONY : TVout.obj

# target to build an object file
TVout.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVout.cpp.obj
.PHONY : TVout.cpp.obj

TVout.i: TVout.cpp.i

.PHONY : TVout.i

# target to preprocess a source file
TVout.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVout.cpp.i
.PHONY : TVout.cpp.i

TVout.s: TVout.cpp.s

.PHONY : TVout.s

# target to generate assembly for a file
TVout.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVout.cpp.s
.PHONY : TVout.cpp.s

TVoutPrint.obj: TVoutPrint.cpp.obj

.PHONY : TVoutPrint.obj

# target to build an object file
TVoutPrint.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVoutPrint.cpp.obj
.PHONY : TVoutPrint.cpp.obj

TVoutPrint.i: TVoutPrint.cpp.i

.PHONY : TVoutPrint.i

# target to preprocess a source file
TVoutPrint.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVoutPrint.cpp.i
.PHONY : TVoutPrint.cpp.i

TVoutPrint.s: TVoutPrint.cpp.s

.PHONY : TVoutPrint.s

# target to generate assembly for a file
TVoutPrint.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TVoutPrint.cpp.s
.PHONY : TVoutPrint.cpp.s

TvOut.obj: TvOut.cpp.obj

.PHONY : TvOut.obj

# target to build an object file
TvOut.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TvOut.cpp.obj
.PHONY : TvOut.cpp.obj

TvOut.i: TvOut.cpp.i

.PHONY : TvOut.i

# target to preprocess a source file
TvOut.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TvOut.cpp.i
.PHONY : TvOut.cpp.i

TvOut.s: TvOut.cpp.s

.PHONY : TvOut.s

# target to generate assembly for a file
TvOut.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/TvOut.cpp.s
.PHONY : TvOut.cpp.s

arduinoRenderer.obj: arduinoRenderer.cpp.obj

.PHONY : arduinoRenderer.obj

# target to build an object file
arduinoRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/arduinoRenderer.cpp.obj
.PHONY : arduinoRenderer.cpp.obj

arduinoRenderer.i: arduinoRenderer.cpp.i

.PHONY : arduinoRenderer.i

# target to preprocess a source file
arduinoRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/arduinoRenderer.cpp.i
.PHONY : arduinoRenderer.cpp.i

arduinoRenderer.s: arduinoRenderer.cpp.s

.PHONY : arduinoRenderer.s

# target to generate assembly for a file
arduinoRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/arduinoRenderer.cpp.s
.PHONY : arduinoRenderer.cpp.s

ball.obj: ball.cpp.obj

.PHONY : ball.obj

# target to build an object file
ball.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/ball.cpp.obj
.PHONY : ball.cpp.obj

ball.i: ball.cpp.i

.PHONY : ball.i

# target to preprocess a source file
ball.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/ball.cpp.i
.PHONY : ball.cpp.i

ball.s: ball.cpp.s

.PHONY : ball.s

# target to generate assembly for a file
ball.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/ball.cpp.s
.PHONY : ball.cpp.s

board.obj: board.cpp.obj

.PHONY : board.obj

# target to build an object file
board.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/board.cpp.obj
.PHONY : board.cpp.obj

board.i: board.cpp.i

.PHONY : board.i

# target to preprocess a source file
board.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/board.cpp.i
.PHONY : board.cpp.i

board.s: board.cpp.s

.PHONY : board.s

# target to generate assembly for a file
board.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/board.cpp.s
.PHONY : board.cpp.s

desktopRenderer.obj: desktopRenderer.cpp.obj

.PHONY : desktopRenderer.obj

# target to build an object file
desktopRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/desktopRenderer.cpp.obj
.PHONY : desktopRenderer.cpp.obj

desktopRenderer.i: desktopRenderer.cpp.i

.PHONY : desktopRenderer.i

# target to preprocess a source file
desktopRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/desktopRenderer.cpp.i
.PHONY : desktopRenderer.cpp.i

desktopRenderer.s: desktopRenderer.cpp.s

.PHONY : desktopRenderer.s

# target to generate assembly for a file
desktopRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/desktopRenderer.cpp.s
.PHONY : desktopRenderer.cpp.s

font4x6.obj: font4x6.cpp.obj

.PHONY : font4x6.obj

# target to build an object file
font4x6.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font4x6.cpp.obj
.PHONY : font4x6.cpp.obj

font4x6.i: font4x6.cpp.i

.PHONY : font4x6.i

# target to preprocess a source file
font4x6.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font4x6.cpp.i
.PHONY : font4x6.cpp.i

font4x6.s: font4x6.cpp.s

.PHONY : font4x6.s

# target to generate assembly for a file
font4x6.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font4x6.cpp.s
.PHONY : font4x6.cpp.s

font6x8.obj: font6x8.cpp.obj

.PHONY : font6x8.obj

# target to build an object file
font6x8.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font6x8.cpp.obj
.PHONY : font6x8.cpp.obj

font6x8.i: font6x8.cpp.i

.PHONY : font6x8.i

# target to preprocess a source file
font6x8.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font6x8.cpp.i
.PHONY : font6x8.cpp.i

font6x8.s: font6x8.cpp.s

.PHONY : font6x8.s

# target to generate assembly for a file
font6x8.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font6x8.cpp.s
.PHONY : font6x8.cpp.s

font8x8.obj: font8x8.cpp.obj

.PHONY : font8x8.obj

# target to build an object file
font8x8.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font8x8.cpp.obj
.PHONY : font8x8.cpp.obj

font8x8.i: font8x8.cpp.i

.PHONY : font8x8.i

# target to preprocess a source file
font8x8.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font8x8.cpp.i
.PHONY : font8x8.cpp.i

font8x8.s: font8x8.cpp.s

.PHONY : font8x8.s

# target to generate assembly for a file
font8x8.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font8x8.cpp.s
.PHONY : font8x8.cpp.s

font8x8ext.obj: font8x8ext.cpp.obj

.PHONY : font8x8ext.obj

# target to build an object file
font8x8ext.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font8x8ext.cpp.obj
.PHONY : font8x8ext.cpp.obj

font8x8ext.i: font8x8ext.cpp.i

.PHONY : font8x8ext.i

# target to preprocess a source file
font8x8ext.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font8x8ext.cpp.i
.PHONY : font8x8ext.cpp.i

font8x8ext.s: font8x8ext.cpp.s

.PHONY : font8x8ext.s

# target to generate assembly for a file
font8x8ext.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/font8x8ext.cpp.s
.PHONY : font8x8ext.cpp.s

frameRate.obj: frameRate.cpp.obj

.PHONY : frameRate.obj

# target to build an object file
frameRate.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/frameRate.cpp.obj
.PHONY : frameRate.cpp.obj

frameRate.i: frameRate.cpp.i

.PHONY : frameRate.i

# target to preprocess a source file
frameRate.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/frameRate.cpp.i
.PHONY : frameRate.cpp.i

frameRate.s: frameRate.cpp.s

.PHONY : frameRate.s

# target to generate assembly for a file
frameRate.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/frameRate.cpp.s
.PHONY : frameRate.cpp.s

game.obj: game.cpp.obj

.PHONY : game.obj

# target to build an object file
game.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/game.cpp.obj
.PHONY : game.cpp.obj

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/game.cpp.s
.PHONY : game.cpp.s

gameConfig.obj: gameConfig.cpp.obj

.PHONY : gameConfig.obj

# target to build an object file
gameConfig.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/gameConfig.cpp.obj
.PHONY : gameConfig.cpp.obj

gameConfig.i: gameConfig.cpp.i

.PHONY : gameConfig.i

# target to preprocess a source file
gameConfig.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/gameConfig.cpp.i
.PHONY : gameConfig.cpp.i

gameConfig.s: gameConfig.cpp.s

.PHONY : gameConfig.s

# target to generate assembly for a file
gameConfig.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/gameConfig.cpp.s
.PHONY : gameConfig.cpp.s

gameStatus.obj: gameStatus.cpp.obj

.PHONY : gameStatus.obj

# target to build an object file
gameStatus.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/gameStatus.cpp.obj
.PHONY : gameStatus.cpp.obj

gameStatus.i: gameStatus.cpp.i

.PHONY : gameStatus.i

# target to preprocess a source file
gameStatus.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/gameStatus.cpp.i
.PHONY : gameStatus.cpp.i

gameStatus.s: gameStatus.cpp.s

.PHONY : gameStatus.s

# target to generate assembly for a file
gameStatus.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/gameStatus.cpp.s
.PHONY : gameStatus.cpp.s

joystickInputDevice.obj: joystickInputDevice.cpp.obj

.PHONY : joystickInputDevice.obj

# target to build an object file
joystickInputDevice.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/joystickInputDevice.cpp.obj
.PHONY : joystickInputDevice.cpp.obj

joystickInputDevice.i: joystickInputDevice.cpp.i

.PHONY : joystickInputDevice.i

# target to preprocess a source file
joystickInputDevice.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/joystickInputDevice.cpp.i
.PHONY : joystickInputDevice.cpp.i

joystickInputDevice.s: joystickInputDevice.cpp.s

.PHONY : joystickInputDevice.s

# target to generate assembly for a file
joystickInputDevice.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/joystickInputDevice.cpp.s
.PHONY : joystickInputDevice.cpp.s

mockInputDevice.obj: mockInputDevice.cpp.obj

.PHONY : mockInputDevice.obj

# target to build an object file
mockInputDevice.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/mockInputDevice.cpp.obj
.PHONY : mockInputDevice.cpp.obj

mockInputDevice.i: mockInputDevice.cpp.i

.PHONY : mockInputDevice.i

# target to preprocess a source file
mockInputDevice.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/mockInputDevice.cpp.i
.PHONY : mockInputDevice.cpp.i

mockInputDevice.s: mockInputDevice.cpp.s

.PHONY : mockInputDevice.s

# target to generate assembly for a file
mockInputDevice.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/mockInputDevice.cpp.s
.PHONY : mockInputDevice.cpp.s

paddle.obj: paddle.cpp.obj

.PHONY : paddle.obj

# target to build an object file
paddle.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/paddle.cpp.obj
.PHONY : paddle.cpp.obj

paddle.i: paddle.cpp.i

.PHONY : paddle.i

# target to preprocess a source file
paddle.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/paddle.cpp.i
.PHONY : paddle.cpp.i

paddle.s: paddle.cpp.s

.PHONY : paddle.s

# target to generate assembly for a file
paddle.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/paddle.cpp.s
.PHONY : paddle.cpp.s

pong_arduino_mock_pong_arduino.ino.obj: pong_arduino_mock_pong_arduino.ino.cpp.obj

.PHONY : pong_arduino_mock_pong_arduino.ino.obj

# target to build an object file
pong_arduino_mock_pong_arduino.ino.cpp.obj:
	$(MAKE) -f CMakeFiles/pong_arduino_mock.dir/build.make CMakeFiles/pong_arduino_mock.dir/pong_arduino_mock_pong_arduino.ino.cpp.obj
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/pong_arduino_mock_pong_arduino.ino.cpp.obj
.PHONY : pong_arduino_mock_pong_arduino.ino.cpp.obj

pong_arduino_mock_pong_arduino.ino.i: pong_arduino_mock_pong_arduino.ino.cpp.i

.PHONY : pong_arduino_mock_pong_arduino.ino.i

# target to preprocess a source file
pong_arduino_mock_pong_arduino.ino.cpp.i:
	$(MAKE) -f CMakeFiles/pong_arduino_mock.dir/build.make CMakeFiles/pong_arduino_mock.dir/pong_arduino_mock_pong_arduino.ino.cpp.i
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/pong_arduino_mock_pong_arduino.ino.cpp.i
.PHONY : pong_arduino_mock_pong_arduino.ino.cpp.i

pong_arduino_mock_pong_arduino.ino.s: pong_arduino_mock_pong_arduino.ino.cpp.s

.PHONY : pong_arduino_mock_pong_arduino.ino.s

# target to generate assembly for a file
pong_arduino_mock_pong_arduino.ino.cpp.s:
	$(MAKE) -f CMakeFiles/pong_arduino_mock.dir/build.make CMakeFiles/pong_arduino_mock.dir/pong_arduino_mock_pong_arduino.ino.cpp.s
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/pong_arduino_mock_pong_arduino.ino.cpp.s
.PHONY : pong_arduino_mock_pong_arduino.ino.cpp.s

randomInputDevice.obj: randomInputDevice.cpp.obj

.PHONY : randomInputDevice.obj

# target to build an object file
randomInputDevice.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/randomInputDevice.cpp.obj
.PHONY : randomInputDevice.cpp.obj

randomInputDevice.i: randomInputDevice.cpp.i

.PHONY : randomInputDevice.i

# target to preprocess a source file
randomInputDevice.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/randomInputDevice.cpp.i
.PHONY : randomInputDevice.cpp.i

randomInputDevice.s: randomInputDevice.cpp.s

.PHONY : randomInputDevice.s

# target to generate assembly for a file
randomInputDevice.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/randomInputDevice.cpp.s
.PHONY : randomInputDevice.cpp.s

schematic.obj: schematic.cpp.obj

.PHONY : schematic.obj

# target to build an object file
schematic.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/schematic.cpp.obj
.PHONY : schematic.cpp.obj

schematic.i: schematic.cpp.i

.PHONY : schematic.i

# target to preprocess a source file
schematic.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/schematic.cpp.i
.PHONY : schematic.cpp.i

schematic.s: schematic.cpp.s

.PHONY : schematic.s

# target to generate assembly for a file
schematic.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/schematic.cpp.s
.PHONY : schematic.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/main.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/main.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/main.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/main.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/main.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/main.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/new.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/new.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/new.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/new.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/new.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/new.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c.s

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.obj: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.obj

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.obj

# target to build an object file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.obj:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.obj
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.obj

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.i: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.i

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.i

# target to preprocess a source file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.i:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.i
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.i

usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.s: usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.s

.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.s

# target to generate assembly for a file
usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.s:
	$(MAKE) -f CMakeFiles/uno_CORE.dir/build.make CMakeFiles/uno_CORE.dir/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.s
.PHONY : usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c.s

video_gen.obj: video_gen.cpp.obj

.PHONY : video_gen.obj

# target to build an object file
video_gen.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/video_gen.cpp.obj
.PHONY : video_gen.cpp.obj

video_gen.i: video_gen.cpp.i

.PHONY : video_gen.i

# target to preprocess a source file
video_gen.cpp.i:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/video_gen.cpp.i
.PHONY : video_gen.cpp.i

video_gen.s: video_gen.cpp.s

.PHONY : video_gen.s

# target to generate assembly for a file
video_gen.cpp.s:
	$(MAKE) -f CMakeFiles/uno_..dir/build.make CMakeFiles/uno_..dir/video_gen.cpp.s
.PHONY : video_gen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pong_arduino_mock-upload"
	@echo "... uno_CORE"
	@echo "... pong_arduino_mock"
	@echo "... uno_."
	@echo "... rebuild_cache"
	@echo "... upload"
	@echo "... pong_arduino_mock-size"
	@echo "... TVOlogo.obj"
	@echo "... TVOlogo.i"
	@echo "... TVOlogo.s"
	@echo "... TVOut.obj"
	@echo "... TVOut.i"
	@echo "... TVOut.s"
	@echo "... TVout.obj"
	@echo "... TVout.i"
	@echo "... TVout.s"
	@echo "... TVoutPrint.obj"
	@echo "... TVoutPrint.i"
	@echo "... TVoutPrint.s"
	@echo "... TvOut.obj"
	@echo "... TvOut.i"
	@echo "... TvOut.s"
	@echo "... arduinoRenderer.obj"
	@echo "... arduinoRenderer.i"
	@echo "... arduinoRenderer.s"
	@echo "... ball.obj"
	@echo "... ball.i"
	@echo "... ball.s"
	@echo "... board.obj"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... desktopRenderer.obj"
	@echo "... desktopRenderer.i"
	@echo "... desktopRenderer.s"
	@echo "... font4x6.obj"
	@echo "... font4x6.i"
	@echo "... font4x6.s"
	@echo "... font6x8.obj"
	@echo "... font6x8.i"
	@echo "... font6x8.s"
	@echo "... font8x8.obj"
	@echo "... font8x8.i"
	@echo "... font8x8.s"
	@echo "... font8x8ext.obj"
	@echo "... font8x8ext.i"
	@echo "... font8x8ext.s"
	@echo "... frameRate.obj"
	@echo "... frameRate.i"
	@echo "... frameRate.s"
	@echo "... game.obj"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... gameConfig.obj"
	@echo "... gameConfig.i"
	@echo "... gameConfig.s"
	@echo "... gameStatus.obj"
	@echo "... gameStatus.i"
	@echo "... gameStatus.s"
	@echo "... joystickInputDevice.obj"
	@echo "... joystickInputDevice.i"
	@echo "... joystickInputDevice.s"
	@echo "... mockInputDevice.obj"
	@echo "... mockInputDevice.i"
	@echo "... mockInputDevice.s"
	@echo "... paddle.obj"
	@echo "... paddle.i"
	@echo "... paddle.s"
	@echo "... pong_arduino_mock_pong_arduino.ino.obj"
	@echo "... pong_arduino_mock_pong_arduino.ino.i"
	@echo "... pong_arduino_mock_pong_arduino.ino.s"
	@echo "... randomInputDevice.obj"
	@echo "... randomInputDevice.i"
	@echo "... randomInputDevice.s"
	@echo "... schematic.obj"
	@echo "... schematic.i"
	@echo "... schematic.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/main.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/main.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/main.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/new.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/new.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/new.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.s"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.obj"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.i"
	@echo "... usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.s"
	@echo "... video_gen.obj"
	@echo "... video_gen.i"
	@echo "... video_gen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

